[[Qt5Base]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5881ce27860bb1d0b536c7ec7e953d8d315642d"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "15c8ffbe9af22d52a116e81e1b722f449be95240d227b2f73fffa6c5d512d320"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "038748adfcdc0a81878cdbaf1d1a15fec7a06d76"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "7050e781edbc87b824f0a3c512a9a1fb0909e8eb49121c830242be112b6f05af"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e905a14b792cd013abcfec9500005a65def9b035"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "04d6b6b38325be97c7cb50e6cdf87113a696a7021919e37b23df0f056cb7dc6e"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Qt5Base]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5fa96492f67c909864af8f9c2130b90f160c537"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "79ad19511c741f91fc98c09383a4ea7a2f2f3fdfe65ea035f1c155be54540ee7"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50d469b43b96f4acfe57a48e469ededea1b6b1e2"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "fa6b3fd1bda32538e15d9685adb494f3fae8f24ca0b4a8c3781f066889863c4d"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.i686-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7c616257e94c7d600376a0c13c4d0b8c5f42358"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "49ccee3b1ac7a1f11f3b855b8ec8829d132d4312e3c615c4ab79643a8dc1c26d"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.i686-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fddf5af6cbd45875fcfb25586c75160a9ef1dc9"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "9cbe3f1ca4fb59070e61b10a1fb2983f8c19f5e46d7cfe41e093d4d3727bb496"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcf75e9534317167bad326833d71fae45543a41e"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "b4c48e42467b19717a19a63729c590a4850878d24b1a1477bb91db99a46293df"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a2ccd3ca1cd3143fce8de3f168fa421c00f38dc"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "22691ea5e7ac472200e20bdd5c7c5cbdbfe120609ca05abaac8b01f4937a1a0b"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "988066cc974e30c89774b0c471f47201975a4423"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "728db67f45e484674c3099ae4825c522684c10f7c2f77b49a8638315ce70253c"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "x86_64"
git-tree-sha1 = "05924641dad6c2d8e2eb528f436241d65ed0a057"
os = "freebsd"

    [[Qt5Base.download]]
    sha256 = "8c1435e863d8a2dcd85466fb3f73680a9030156b4860c425c2145165879cc29e"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.x86_64-unknown-freebsd.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8924c1df9a1e924ffde6d22a287b9147b595939f"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "5e0966a3be81df77be2a5af4e86076e6269857dcd89e8b1716ed492b4d117e8d"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.i686-w64-mingw32-cxx03.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f1af4a4f507a880e2a01bb67384e530ee640676"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "6110d645290dffcab21476560b0e2b937d934d8cb2f0ce43db469915f28a4fa5"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.i686-w64-mingw32-cxx11.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04a56e6bbe485bb92c042a00e68c679ff24c85cc"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "ea369a1a2e5727405333bee857f1b12030d46ddbae17c4732e5e1626d83de9b8"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3712e14d6f387fa0a6d1509acbdd4b8976e87d1"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "5e50b5fdbab4123f41c5e9e4c40bf2701c7ad304a480b0ee244cb745fdeb91c8"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt5Base]]
arch = "aarch64"
git-tree-sha1 = "24182276d53e7c2e1d8e93cad55cfd0102cf442e"
os = "macos"

    [[Qt5Base.download]]
    sha256 = "5e6591b1684a7007b6bdc22240c6adbc5af08452dd9cf62a3ed7534777a7fb4b"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.aarch64-apple-darwin.tar.gz"
[[Qt5Base]]
arch = "x86_64"
git-tree-sha1 = "a0db4e704fd0da4298744f012883535d351fa170"
os = "macos"

    [[Qt5Base.download]]
    sha256 = "d6ce627851a8a75524e361a10b194e4baf1ccf870bfcfc5923a11494e5cc1dae"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+1/Qt5Base.v5.15.3.x86_64-apple-darwin.tar.gz"
