[[Qt5Base]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d35264905d7966cd93f9a3e7bf4189e5214a1c51"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "9d8c3ff85663a6e241e02539e1460fadefd6a16491fb5240b10e066a31f8c82e"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af4677c94c42c53876db4993996f3b7a6fd63728"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "db79e4444923b07dae8ca6e38018a30e966fa75dd37c138003778fcec8599c6b"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15201bc7f73ab2bc686e0f5acfddca66bfba09fa"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "4e3b7469429ade05f0cd9a2b273c315d0c8ce132e992b7939662284e5cdb4367"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Qt5Base]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fae447dd0bc84d1808a0938b2a9536227fca9176"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "eddd6c6f7de484e7612e48a73f270ffa8d6bddc4847bff9e981476c7730b15cd"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c3e69595311d4f8cb2ab48acbde4a856923e3b3"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "8161524163089921e79be2ca09443f9c7915b68e233d893505705ff966bd4f62"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.i686-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f40e730be8e28d878417ea1b890c09e5bbb1dd96"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "9d87f6f2ae0a8a8a38197f34c88d8bde2b246864b1b0b0f16a93669e6e161d70"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.i686-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "308cd2e31407969e5a25b7a49221e8acf70fb57e"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "a645efa5b228659112a52baf0597d2ebc824be2c61dce9aaecf4bae51c6aa5f5"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "165782e06c6ac1ff4b513ec0cb07c638cb02a115"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "60bdbc25bcd69d14466957ccf401fb2b92cd30e9d9f6eaac15bbff636ea53e7e"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf5eab0166258d74dfb0ad8308ca35240577d398"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "99e7be1169a5acd2481fc9cff46b3dd9095738b3765f2f341e630b21fedc9ab3"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "388246ba5e10de0b457ad8a6a855a6603afc7378"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "4a94d0efdd92d63f073a4f7a40cce8e97f0b354d73c894dff7b73f347a9f55db"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "x86_64"
git-tree-sha1 = "75d10b8c3abdd552ef54c167d8352f8cf2a56ba3"
os = "freebsd"

    [[Qt5Base.download]]
    sha256 = "9a70cb5c605874fec688d7c83509c436de96adf0a6660739afc6195c37b94c03"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.x86_64-unknown-freebsd.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60e17392cb4409cbf37f4716120c88376ea7dfb2"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "030c16f2a9665815cd54e34a4d052498e19cba13154f18cab145debb23add16d"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.i686-w64-mingw32-cxx03.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83120049e60358488a32ec65a42aa23a87e11cc0"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "53aca99d27590abc61e81b61d383bde40a6f7437d5f6951ed84dd50ad4b2a4cf"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.i686-w64-mingw32-cxx11.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59c11a6edbba1f76cbb15352121ff2521c4759de"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "7fd081b1534257899fa6dc3f1ca4afebfaa41da6587d3c412dec5d5ddba599ef"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14c036187f02f2def7e45b19b27ea5d4a5873e21"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "548cf5b5bfe937e4391a63ace768f9c2ea04593fa676a7300273d173c8f52473"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt5Base]]
arch = "aarch64"
git-tree-sha1 = "b37aebc8943f796682edea53e2ec10463bf624ac"
os = "macos"

    [[Qt5Base.download]]
    sha256 = "22c26a5cbe9af1cd0cf87046bf701e18f8ce1e6984646708729c47928387db48"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.aarch64-apple-darwin.tar.gz"
[[Qt5Base]]
arch = "x86_64"
git-tree-sha1 = "5cb67771651635f5ac02f3a60017effcbeebb119"
os = "macos"

    [[Qt5Base.download]]
    sha256 = "c9226e8f1ded00487d4aee9a0954d72eaf156bf8075f892718b2c78753d9a80a"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.x86_64-apple-darwin.tar.gz"
